USE user_db;

-- BCrypt hash for 'test1234!' (generated by live user-service)
UPDATE users 
SET password = '$2a$10$L1rLPXuTB/RmhVwm7IdcLeLd93siSnP0qtEQK.1o32C4JZdIO8fe.'
WHERE email IN ('visitor@sparta-msa.com', 'admin@sparta-msa.com');

-- cleanup temp account
DELETE FROM users WHERE email = 'temp_hash_gen@test.com';
