USE user_db;

-- Delete test users and re-insert with CORRECT BCrypt hash for 'test1234!'
-- Hash generated by live user-service BCryptPasswordEncoder
DELETE FROM users WHERE email IN ('visitor@sparta-msa.com', 'admin@sparta-msa.com');

INSERT INTO users (email, password, name, phone_number, gender, role, is_active)
VALUES 
('visitor@sparta-msa.com', '$2a$10$L1rLPXuTB/RmhVwm7IdcLeLd93siSnP0qtEQK.1o32C4JZdIO8fe.', '테스터', '010-1234-5678', 'MALE', 'USER', true),
('admin@sparta-msa.com', '$2a$10$L1rLPXuTB/RmhVwm7IdcLeLd93siSnP0qtEQK.1o32C4JZdIO8fe.', '관리자', '010-9876-5432', 'FEMALE', 'ADMIN', true);
