apiVersion: v1
kind: ConfigMap
metadata:
  name: sparta-msa-config
  namespace: sparta-msa
data:
  MYSQL_ROOT_PASSWORD: "password"
  JWT_SECRET: "your-256-bit-secret-key-here-minimum-32-characters-required"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
