input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [message] =~ /^\{.*\}$/ {
    json {
      source => "message"
      target => "parsed_message"
    }
  }

  mutate {
    add_field => {
      "environment" => "docker"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "msa-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
