apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: sparta-msa
spec:
  replicas: 1
  progressDeadlineSeconds: 2700
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:TieredStopAtLevel=1 -Xmx384m -Xms64m -XX:MaxMetaspaceSize=112m -XX:ReservedCodeCacheSize=32m -XX:+ExitOnOutOfMemoryError"
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/payment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sparta-msa-config
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_DATA_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: sparta-msa-config
              key: REDIS_HOST
        - name: SPRING_DATA_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: sparta-msa-config
              key: REDIS_PORT
        - name: KAFKA_SERVERS
          value: "kafka:9092"
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: sparta-msa-config
              key: JWT_SECRET
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8084
          initialDelaySeconds: 60
          failureThreshold: 150
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8084
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 6
        resources:
          requests:
            cpu: "200m"
            memory: "384Mi"
          limits:
            cpu: "2000m"
            memory: "2048Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: sparta-msa
spec:
  ports:
  - port: 8084
    targetPort: 8084
  selector:
    app: payment-service
